### ISSUE TITLE
Allow the backgroundImagePanel to have video backgrounds

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#151]
Im not sure how this would work exactly, but it’d be really neat if we added the ability for blocks that use background images to also support background videos.

**Comment by richtabor** [comment]
@phpbits Do you want to explore how this would work perhaps?

**Comment by phpbits** [comment]
@richtabor We will be needing extra js file for this one ( fitvids, I think ). Or we can use fixed video with 100% width and height of the container. What do you think?

**Comment by richtabor** [comment]
We can try it without JS but we may need to load on the frontend like we do with the Map block.

**Comment by richtabor** [comment]
We could maybe do it like this Coverr does: https://coverr.co

Or perhaps using this method: https://www.w3schools.com/howto/howto_css_fullscreen_video.asp

**Comment by phpbits** [comment]
@richtabor I've created `video-background` branch and applied video background option to hero block. Let me know your thoughts. Thanks!
