### ISSUE TITLE
Format is already registered issue with Gutenberg 5.0

### ISSUE THREAD

**Issue by phpbits** [coblocks/coblocks#249]
Install Gutenberg 5.0 then load the editor. Console is logging this

<img width="1274" alt="screen shot 2019-02-08 at 12 57 06 pm" src="https://user-images.githubusercontent.com/3365507/52459596-16936c00-2ba1-11e9-9e4d-5d55fd2e09d2.png">

**Comment by richtabor** [comment]
Issue on the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/13776

**Comment by richtabor** [comment]
Issue is no longer present in Gutenberg 5.3

**Comment by phpbits** [comment]
Nice 👍
