### ISSUE TITLE
Add Welcome admin view

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#265]
**Is your feature request related to a problem? Please describe.**
Onboarding with CoBlocks is non-existent. We don't have much documentation, nor help videos. We could help folks quite a bit by adding a simple welcome view. 

**Describe the solution you'd like**
When you first activate CoBlocks, there should be a "Welcome to CoBlocks" type page where we feature a guide to help kick off working with our blocks and tools. We should also provide links to more detailed resources and documentation (which also do not currently exist). 

**Additional context**
WP Forms seems to do this in a simple fashion that I think is on the right track. What I don't like is that once you leave that welcome view, it's not possible to go back to it. We should have a link to the welcome view within our new "CoBlocks" admin menu item - possibly titled "Welcome."

**Comment by richtabor** [comment]
Recording from WPForms: ![screenflow](https://user-images.githubusercontent.com/1813435/52538122-ae798d00-2d3c-11e9-99e0-13e5a35aa43e.gif)

**Comment by richtabor** [comment]
And here's the internal link to our research card on Trello: https://trello.com/c/tCj6W55U/1057-welcome-view

**Comment by phpbits** [comment]
@richtabor @alexdenning I've created `welcome-view` branch. Here's what I've came up so far. For sure Rich will make it a lot better :) 

![screen capture on 2019-02-12 at 13-14-22](https://user-images.githubusercontent.com/3365507/52613302-57082800-2ec8-11e9-97d4-51e53f86f272.gif)

**Comment by alexdenning** [comment]
Here's the text I'd want on the page:

### Welcome to CoBlocks, the page builder for Gutenberg

👋 Thanks for installing CoBlocks! You've just added both lots of extra useful blocks _and_ a page builder system to the new WordPress editor.

CoBlocks gives you a **game-changing combination of features**: new blocks, a true page-builder experience for Gutenberg, custom typography controls, and a Block Manager for turning blocks on-and-off 🏗

Here's a quick getting started video which shows you what you can do ⤵️

embed video

Buttons – [Create Your First Page] and [View All Tutorials]

Thanks for using CoBlocks! 💪 If you have any queries or feedback, [let us know on Twitter](https://twitter.com/coblocks) or [through our Facebook group](https://www.facebook.com/groups/coblocks). We are CONSTANTLY adding new features, so if you want to see what's new [you can join our mailing list here](https://coblocks.us20.list-manage.com/subscribe?u=fd78cec472f9f62b76fca64d1&id=62cbc3526f).

Cheers! Rich, Jeffrey, and Alex 🙌

**Comment by richtabor** [comment]
Good deal @alexdenning. Mind if we trim up emojis a bit though?

**Comment by richtabor** [comment]
@phpbits Here's the video: https://www.youtube.com/watch?v=EsIpvCcTKPw

**Comment by richtabor** [comment]
And here's the "View Tutorials" link: https://www.youtube.com/playlist?list=PLOX73tMRtakRvlWj0ltakB27F0NA0OGT3

**Comment by spencerfinnell** [comment]
> for Gutenberg
> to the new WordPress editor

I think those should match (and probably both reference "new WordPress editor")

**Comment by richtabor** [comment]
> > for Gutenberg
> > to the new WordPress editor
> 
> I think those should match (and probably both reference "new WordPress editor")

@spencerfinnell I'm thinking "new WordPress block editor" - what do you think?

**Comment by spencerfinnell** [comment]
I like that.

**Comment by phpbits** [comment]
@richtabor @alexdenning I've changed the content, not sure about the right alignment though. 
![screen capture on 2019-02-19 at 00-12-29](https://user-images.githubusercontent.com/3365507/52963597-30238780-33db-11e9-9c96-b28acbb9bb7e.gif)

**Comment by richtabor** [comment]
I’ll tweak the styling. 💪
