### ISSUE TITLE
Add Hero block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#267]
**Is your block idea related to a problem? Please describe.**
Most landing pages have bold hero areas at the top. This block would serve that need.

**Describe what you’d like the block to do**
We need the Hero block to empower folks to build beautiful areas (primarily at the top of a page) that will properly introduce the page and provide a call to action(s) for their visitors to interact with. 

The following actions should be supported: 
1. Use InnerBlocks to display a Heading, Paragraph and our Buttons block.
2. Background image, including overlay (using our custom component) - along with our background image drop zone. 
3. backgroundColor and textColor. The heading and text elements are using InnerBlocks, so their styling should override the parent Hero block’s color settings. 
4. Adjust the block padding using the DimensionsControl. As with our other blocks, adding a backgroundColor or backgroundImage automatically sets the padding to ‘Medium’ if there is no padding already. 

The following actions would be really nice to have: 
1. Have a ToggleControl to make the Hero block display at the full height of the viewport. The content should be vertically centered (likely with flex box?). If it’s turned on, maybe an animated "scroll-down" arrow appears at the bottom of the block.
2. Consider including an inverted Shape Divider block on the bottom of the Hero block (if it works out well within InnerBlocks to do so). If it’s added to the block TEMPLATE, along with a background color that matches the default Hero background color. But how would folks turn off the divider, if they don't want it. Maybe it'd just require them deleting it. 
3. Maybe have an option to have the Hero block's content displaying at the top left, top right, top center, bottom left, bottom center, bottom right, and completely centered. We could build a custom component that looks like a selection grid where users select which "box" to display their content in. Would likely use CSS grid. 

**Name**
It should be called the "Hero" block.

**Icon**
[Click here](https://github.com/coblocks/coblocks/files/2849372/hero.svg.zip) to download the icon.

**Description**
An introductory area of a page accompanied by a small amount of text and a call to action. 

**Block Toolbar Controls **
The block toolbar should comprise of left/center/right alignment settings, using the AlignmentToolbar core component. It will text-align the contents of the Hero block to the left, right and center.

**Comment by richtabor** [comment]
> 3. Maybe have an option to have the Hero block's content displaying at the top left, top right, top center, bottom left, bottom center, bottom right, and completely centered. We could build a custom component that looks like a selection grid where users select which "box" to display their content in. Would likely use CSS grid.

Something like this, where each grid item is selectable - and fills with blue when active:
<img width="584" alt="screen shot 2019-02-10 at 7 41 44 pm" src="https://user-images.githubusercontent.com/1813435/52542261-07ace500-2d6c-11e9-8f91-499c5ae6993c.png">

**Comment by richtabor** [comment]
We should also support the FocalPointPicker

**Comment by phpbits** [comment]
@richtabor I'm trying not to recreate those settings and used our Row Block instead. I've created a new `hero-block` branch. Instead of us controlling padding of hero section via CSS, I'm just creating innerblocks and setting padding attributes. It's easier for us to manage too, just like what we did on Media Card. 

Question though, do you have idea in mind on how we can do fullscreen on editor view? Seems like `vh` is not working. I've only added 3 layout options for now since I can't figure out the editor full height view. Let me know your thoughts :)

**Comment by phpbits** [comment]
Forgot to ask, I think we can do similar UX as our Row Block. We can do layout selection after adding blocks, so user knows that we have multiple layouts :)

**Comment by richtabor** [comment]
> @richtabor I'm trying not to recreate those settings and used our Row Block instead. I've created a new `hero-block` branch. Instead of us controlling padding of hero section via CSS, I'm just creating innerblocks and setting padding attributes. It's easier for us to manage too, just like what we did on Media Card.

Yea, that's great. I think it's working nicely!

**Comment by richtabor** [comment]
> Question though, do you have idea in mind on how we can do fullscreen on editor view? Seems like `vh` is not working. I've only added 3 layout options for now since I can't figure out the editor full height view. Let me know your thoughts :)

I was about to get 100vh working, though it's not a one-to-one representation of the frontend (won't likely be) because it's set within so many divs/etc. Its just as tall as what we'd see on the frontend though.

I applied the `height: 100vh;` to the `.wp-block-coblocks-row__inner`

**Comment by richtabor** [comment]
> I think we can do similar UX as our Row Block. We can do layout selection after adding blocks, so user knows that we have multiple layouts :)

@phpbits Are you think something like the Row Block > Layouts section (both in the control toolbar and the sidebar)?
<img width="311" alt="screen shot 2019-02-14 at 6 59 32 am" src="https://user-images.githubusercontent.com/1813435/52785487-1c1c0680-3026-11e9-8b1f-ca2bc1730f03.png">

**Comment by phpbits** [comment]
> @phpbits Are you think something like the Row Block > Layouts section (both in the control toolbar and the sidebar)?

This one actually, the layout on the inspector control will be the grid you have on sketch.

<img width="701" alt="screen shot 2019-02-14 at 9 43 36 pm" src="https://user-images.githubusercontent.com/3365507/52790544-ca18c680-30a1-11e9-9cd8-234ed861dec1.png">

**Comment by richtabor** [comment]
That's an interesting approach, but I think in this capacity we should have the Hero block added as quickly as possible - with an option to change the layout (even using the same visualDropdown component and such like we do in the Row block). 

The difference between the Row block layout and the Hero block layout is that the Row block _needs_ a layout selected before it can render something - whereas the Hero block does not.
