### ISSUE TITLE
Add the FocalPointPicker component to BackgroundImagePanel

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#268]
**Is your feature request related to a problem? Please describe.**
Folks should be able to set a focal point for background images.

**Describe the solution you'd like**
Add support for the new [FocalPointPicker](https://github.com/WordPress/gutenberg/blob/77f617603bb369cd16e8ed76ef636b2b82afaaac/packages/components/src/focal-point-picker/README.md) component to our own BackgroundImagePanel component.

**Additional context**
We need to make sure we have deprecations in place if adding this would break users' existing blocks with background images. 

**Screenshots**
![focla](https://user-images.githubusercontent.com/1813435/52539520-f6a0ab80-2d4c-11e9-8513-049d4e4a296d.jpg)

**Comment by richtabor** [comment]
I'm not sure if our "Position" select control would be relevant then? We'll have to see what happens.

**Comment by phpbits** [comment]
@richtabor Added on Media Card :) Let me know your thoughts and will add FocalPointPicker on other blocks that has Background Image Panel. 👍

**Comment by richtabor** [comment]
It looks good!

**Comment by richtabor** [comment]
@phpbits One question though. By adding this, we're effectively raising the minimum version number to WordPress 5.1, correct? As anyone using an older version of Gutenberg/WordPress won't have the FocalPointPicker. 

Is there a way to check to see if the component is available so it doesn't through the "The editor has encountered an unexpected error." notice?

**Comment by phpbits** [comment]
@richtabor Didn't thought of that, this should be core notice but will check if there's any way to check version or something like function_exists.

**Comment by phpbits** [comment]
@richtabor I'm using AND as condition here though : https://github.com/coblocks/coblocks/blob/ccd9fb21d4437c0a8bcc53653357385fbd40b12d/src/components/background/index.js#L133 . Which probably will prevent the issue.

**Comment by phpbits** [comment]
@richtabor Added on the following blocks:

- [ ] Row

- [ ] Column

- [ ] Media Card

- [ ] Features

- [ ] Feature

**Comment by richtabor** [comment]
> @richtabor Didn't thought of that, this should be core notice but will check if there's any way to check version or something like function_exists.

It stems from the FocalPointPicker component just not existing in core/older version of Gutenberg. Right now, it throws an error if I turn off the 5.0 Gutenberg plugin.

**Comment by richtabor** [comment]
> > @richtabor Didn't thought of that, this should be core notice but will check if there's any way to check version or something like function_exists.
> 
> It stems from the FocalPointPicker component just not existing in core/older version of Gutenberg. Right now, it throws an error if I turn off the 5.0 Gutenberg plugin.

@phpbits Have any thoughts on this? Or do we have to then update our `Requires at least` value to `5.1` then?

**Comment by phpbits** [comment]
@richtabor Updated to fix the issue with installations w/o FocalPointPicker 🥇
