### ISSUE TITLE
Image overlay on Column block is positioning on top of content

### ISSUE THREAD

**Issue by uamv** [coblocks/coblocks#278]
**Describe the bug**
The overlay on columns with a background image and containing a button (or possibly other clickable elements) renders the elements unclickable. Probably a z-index issue.

**To Reproduce**

1. Create row with single column.
1. Set background.
1. Add image overlay.
1. Insert button block in the column.

**Expected behavior**
I'd expect the button to remain clickable even when the containing column has a background with an image overlay.

**Screenshots**
![coblocks-element-unclickable-w-overlay](https://user-images.githubusercontent.com/6343951/52666027-1239bc80-2edb-11e9-92ad-d10ad5e0a285.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - Browser: Chrome
 - Version 71.0.3578.98

**Comment by richtabor** [comment]
Hey @uamv, what theme are you using? I'm not able to replicate that on Twenty Nineteen or the CoBlocks theme.

**Comment by uamv** [comment]
I'm running a child of GeneratePress. However, I did switch to Twenty Nineteen and was still encountering the issue. I also replicated in a fresh WP install w/ only Coblocks active. Here's a [screencast of that](https://drive.google.com/file/d/15SwsXIVPHBKrHgVXdjpf0UuWa6t_aUOB/view?usp=sharing).

**Comment by richtabor** [comment]
Ahh, that's for that video @uamv — makes it much clearer. I was adding the background image to the Row block, not the column. Yup, we'll get this tweaked. 👌

**Comment by richtabor** [comment]
@phpbits I was able to reproduce this, by adding a background image to the column block, not the row block. This is another reason why I'm thinking it may be best for singular column row blocks to not have a column inside of it via the TEMPLATE. As it can get confusing adding margin/padding/backgrounds to a column and to a row (when they are essentially the same). 

What are your thoughts?

**Comment by uamv** [comment]
> I was adding the background image to the Row block, not the column.

I thought it'd make more sense to add a background image to the row block, but I've not been able to find that option anywhere. It appears that it may not be available on rows with a single column.

> As it can get confusing adding margin/padding/backgrounds to a column and to a row (when they are essentially the same).

I can confirm. This does get confusing.

**Comment by richtabor** [comment]
@uamv It's possible to drag and drop in images into rows and columns, but you're right - I made an issue earlier (#301) uncovering that the single column row block was not properly showing the upload and delete background image icons in the control toolbar. We'll have a fix for that also in 2.0.

**Comment by phpbits** [comment]
@richtabor @uamv I've created branch `column-image-overlay-fixes` to fix the issue but adding `position:relative` to blocks inside column with overlay. Let me know if it's working perfectly on your end too!

**Comment by richtabor** [comment]
It works fine with divs that have `wp-block` in the class, but it's not for paragraphs (and I suspect for heading/anything that does not have `wp-block` in the className. 
<img width="454" alt="screen shot 2019-02-18 at 8 44 04 pm" src="https://user-images.githubusercontent.com/1813435/52984601-27708880-33be-11e9-8736-7925f05203f8.png">

**Comment by phpbits** [comment]
@richtabor How using ` > *` instead of `> [class*="wp-block-"]` ?

**Comment by phpbits** [comment]
@richtabor Added the changes. Thanks!

**Comment by richtabor** [comment]
That works!
