### ISSUE TITLE
Set the initial state of the Hero block to fullwidth

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#293]
We should have the initial alignment state set to fullwidth for when a user first adds the Hero block. Also, it should only be set to wide, if a theme supports it. [Here's](https://github.com/thatplugincompany/block-gallery/blob/master/src/components/size-control.js#L209-L213) how I did that in Block Gallery previously, using getEditorSettings.

<img width="1061" alt="screen shot 2019-02-14 at 6 08 52 am" src="https://user-images.githubusercontent.com/1813435/52783159-0d7e2100-301f-11e9-800d-f42b53fc49a8.png">

**Comment by richtabor** [comment]
Actually, it looks like TwentyNineteen does this already - just not the CoBlocks theme. 🤔

This could be related to this issue [here](https://github.com/coblocks/coblocks/issues/266) about the singular Row block being odd in the CoBlocks theme. I'll look into this one @phpbits.

![screenflow](https://user-images.githubusercontent.com/1813435/52784508-5a63f680-3023-11e9-9980-185230db4ac8.gif)

**Comment by phpbits** [comment]
@richtabor I'm using CoBlocks too and it's working fine. Would you mind checking the latest branch. Thanks!

**Comment by richtabor** [comment]
> @richtabor I'm using CoBlocks too and it's working fine. Would you mind checking the latest branch. Thanks!

You're right - it's working fine now. 👍
