### ISSUE TITLE
Odd spacing behavior with stacked buttons on the Buttons block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#295]
The button gutter works great when the buttons are not stacked, but when they are, there's some odd behavior going on.

Here's a recording:
![screenflow](https://user-images.githubusercontent.com/1813435/52784296-a8c4c580-3022-11e9-9117-e0ea128db9f2.gif)

**Comment by richtabor** [comment]
Related: https://github.com/coblocks/coblocks/issues/274

**Comment by phpbits** [comment]
@richtabor Fixed 👍

**Comment by richtabor** [comment]
Perfect!
