### ISSUE TITLE
Remove the extra space at the bottom of the Hero block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#296]
Instead of using an Advanced setting for the padding by default, we should figure out a cleaner solution to removing the extra spacing within the editor - as we'll likely have the option for admins to turn off advanced type controls. 

I think this would do it: 
![screenflow](https://user-images.githubusercontent.com/1813435/52784670-dfe7a680-3023-11e9-8e6c-506e6fd3be8d.gif)

**Comment by phpbits** [comment]
@richtabor Fixed itself when I've removed the Row Block :)
