### ISSUE TITLE
Improve how blocks are added to columns within the Row block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#300]
We've received a number of reviews/feedbacks suggesting that adding blocks to columns within Row blocks is quite difficult. Most common, folks are adding them elsewhere - then dragging them into the columns. I think we can come up with a clever solution, which makes adding blocks much more logical. 

For myself, and other power-users, it's easy to do the "/" command and add a block. But for normal folk, it's not as intuitive. 

**Here is what we have currently:** 
![screenflow](https://user-images.githubusercontent.com/1813435/52792815-45469200-303a-11e9-9bdf-dccbebb25a0d.gif)

**Here is a rough idea:** 
![screen-shot-2019-02-14-at-9 26 27-am](https://user-images.githubusercontent.com/1813435/52793195-33b1ba00-303b-11e9-9b2c-70748ca24fe1.jpg)

Ideally, the "+ Add block" would pull up the block inserter. I'm not sure if it should stay at the bottom of the column, or if it should only be there for the initial state (if there are no blocks added to the column). 

What do you think @phpbits?

**Comment by phpbits** [comment]
@richtabor I think it's doable but I think it's better if we use the same styling as our "Add Accordion Item" button. It looks better when blocks are already available inside the column. We will just show the button on `is-selected` and initial state. What do you think?

<img width="671" alt="screen shot 2019-02-14 at 10 39 53 pm" src="https://user-images.githubusercontent.com/3365507/52793841-9c378000-30a9-11e9-8477-68a8aeee71cd.png">

**Comment by richtabor** [comment]
> @richtabor I think it's doable but I think it's better if we use the same styling as our "Add Accordion Item" button. It looks better when blocks are already available inside the column. We will just show the button on `is-selected` and initial state. What do you think?
> 
> <img alt="screen shot 2019-02-14 at 10 39 53 pm" width="671" src="https://user-images.githubusercontent.com/3365507/52793841-9c378000-30a9-11e9-8477-68a8aeee71cd.png">

Yup that works!

**Comment by phpbits** [comment]
Starting to make some progress 👍 
![screen capture on 2019-02-15 at 22-22-55](https://user-images.githubusercontent.com/3365507/52862609-9e184680-3170-11e9-8720-331c1803404a.gif)

**Comment by phpbits** [comment]
@richtabor I've created `column-block-improvement` branch. Let me know your thoughts. Thanks!

**Comment by richtabor** [comment]
Looks good! I've merged it back with `layout-block` branch. Next time, we need to keep the branches based from `master` as much as possible (esp if they are localized within a particular block/sidebar/etc).
