### ISSUE TITLE
BackgroundImageToolbarControls is missing from the singular column Row block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#301]
The Row block is missing the BackgroundImageToolbarControls, if it's set to display as a one column. That's because currently, a `layout` is needed for them to display ([code source](https://github.com/coblocks/coblocks/blob/master/src/blocks/row/components/controls.js#L101)). As a one column Row block does not have a layout, the controls are not showing.

**Screenshot**
<img width="1511" alt="screen shot 2019-02-14 at 9 36 47 am" src="https://user-images.githubusercontent.com/1813435/52793605-14fff300-303c-11e9-92cb-716e326a56a4.png">

**Expected behavior** 
The singular column row block should have the controls as needed. We need a better if statement which does not rely on layout, or also returns `true` if the `columns` is set to 1

**Comment by phpbits** [comment]
@richtabor Fixed and created PR : https://github.com/coblocks/coblocks/pull/303 👍
