### ISSUE TITLE
Social block li::before should be set to display:none

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#307]
Some themes apply a custom list style using `li::before { content: '' }`. We should add a display: none style to those list items to ensure they do not happen on our Social block. 
 
<img width="393" alt="screen shot 2019-02-15 at 7 57 41 pm" src="https://user-images.githubusercontent.com/1813435/52891909-fee95400-315b-11e9-9c55-f22049efee5f.png">

**Comment by phpbits** [comment]
@richtabor Created `social-block-fixes` based from master with fixes 👍
