### ISSUE TITLE
Single column Row block is not working properly with the new inserter UI

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#315]
I'm on the `layout` branch which now has the new Row block UI. Single column Row blocks are throwing the following error:

![screenflow](https://user-images.githubusercontent.com/1813435/52985528-39ecc100-33c2-11e9-90a8-1092a1654436.gif)

**Comment by phpbits** [comment]
@richtabor Fixed 👍

**Comment by phpbits** [comment]
I've forgot to add the inserter button on Single column :D
