### ISSUE TITLE
Enable/disable blocks by role

### ISSUE THREAD

**Issue by gtermini** [coblocks/coblocks#318]
**Is your feature request related to a problem? Please describe.**
In order to deploy CoBlocks in a large CMS environment, with hundreds of editors authoring sections of a given website, it would be great if we could give access to only certain blocks to users in a given role. For example: "Editors" can add/edit/delete Map blocks, but "Authors" can't. To make this even more suitable for an enterprise CMS deployment (and get brownie points!) administrators would be able to determine what actions those categories can perform on given blocks: drag&drop, edit, delete. This would be useful if I have a block that I don't wan't editors to move (for example, a contextual navigation block that should always be in the same spot on the page). It would come built-in with preconfigured templates, that Editors would use as a boilerplate solution to start new pages. This is already possible in other Page Builders, for example in Visual Composer: https://www.youtube.com/watch?time_continue=80&v=HiO_ksIK-kk It would be great if Gutenberg could be used this way.

**Describe the solution you'd like**
Something like https://www.youtube.com/watch?time_continue=80&v=HiO_ksIK-kk

**Describe alternatives you've considered**
WPBakery Page Builder

**Comment by richtabor** [comment]
Thanks @gtermini - this is certainly possible within Gutenberg. It's just a matter of figuring out the best way to do it. It's not on our immediate roadmap, but this is something I'd like to do for sure.

**Comment by gtermini** [comment]
Thank you for considering this feature!

**Comment by richtabor** [comment]
We're likely going to move forward with deprecating our custom Block Manager as core has now included one inspired by our own in Gutenberg 5.3 and the upcoming WordPress 5.2 release. 

https://github.com/coblocks/coblocks/issues/400

**Comment by gerlandotermini** [comment]
This is great news! Thank you.
