### ISSUE TITLE
Hero Block Content Width setting should be maxWidth, instead of width

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#321]
For improved responsiveness, it'd be better to have the content width setting set with a maxWidth inline style, instead of width (which does not work well on mobile).

**Comment by phpbits** [comment]
@richtabor `width` is needed because we are using grid. I'll just max-width via CSS. Thanks!

**Comment by richtabor** [comment]
> @richtabor `width` is needed because we are using grid. I'll just max-width via CSS. Thanks!

We can't use `width` as a hard value in the CSS though, as it does this on mobile: 
<img width="524" alt="screen shot 2019-02-20 at 12 50 04 pm" src="https://user-images.githubusercontent.com/1813435/53112803-1898eb80-350e-11e9-9163-672374f0567b.png">

**Comment by phpbits** [comment]
@richtabor Yeah, just saw that too. But if we use `max-width` the width of the grid isn't changing :D I'll figure it out ;)
