### ISSUE TITLE
Could we use a ResizableBox to set the content width in the Hero block?

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#322]
Do you think it's possible we could use a ResizableBox component that wraps the content to where users can drag the content max-width? 

It could perhaps be as simple as this: 
<img width="918" alt="screen shot 2019-02-20 at 8 24 41 am" src="https://user-images.githubusercontent.com/1813435/53094731-fc368800-34e8-11e9-92e9-337cc5a1c3a5.png">

And when dragged, a vertical border appears (like the horizontal borders do on the Shape Divider).

**Comment by phpbits** [comment]
@richtabor I'm actually about to add this one 👍

**Comment by phpbits** [comment]
@richtabor Added the vertical line when resizing :)
