### ISSUE TITLE
If Hero block content is centered, center the heading::before

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#323]
To resolve themes which may add a heading ::before style, like TwentyNineteen.

<img width="1344" alt="screen shot 2019-02-20 at 8 28 42 am" src="https://user-images.githubusercontent.com/1813435/53094967-8a127300-34e9-11e9-8c0c-db84cbb2d360.png">

```
h1:before,
h2:before {
margin-left: auto;
margin-right: auto;
}
```

**Comment by phpbits** [comment]
@richtabor Added 👍

**Comment by richtabor** [comment]
@phpbits We also need to do it for when the heading is right aligned.

But, I think we may need to tweak it a bit, as with #324, we should not auto-align the text with the layout selected. Instead, we use should the AlignmentToolbar component and let the user select text alignment. Perhaps we should have a class assigned based on the alignment? 

Here's how we do it in Features: 
`[ `has-${ contentAlign }-content` ]: contentAlign,`

**Screenshot:**
 ![screenflow](https://user-images.githubusercontent.com/1813435/53104515-7f61d900-34fd-11e9-9554-8cece23f4e23.gif)
