### ISSUE TITLE
Instead of defining content alignment, let's add a AlignmentToolbar to the Hero block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#324]
This way, folks will have more ways to style the hero block. 

We should remove the auto applied text alignment and let users control it with the core AlignmentToolbar on the Hero block BlockControls.

**Comment by richtabor** [comment]
We could set the text alignment attribute (`contentAlign`) to center, if a center layout is chosen - to still achieve that look automatically. Then the user can set the alignment back to left, or right if they'd like. I think that's a good idea.

**Comment by phpbits** [comment]
@richtabor I'm currently setting all innerblocks to change attributes for alignment, do you think it's a good idea? Or I just add class to the hero block and change the alignment via CSS. Let me know your thoughts. Thanks!

**Comment by richtabor** [comment]
I think we add a content class to the hero, as referenced in [this comment here](https://github.com/coblocks/coblocks/issues/323#issuecomment-465637037). Just like how the Features block has an alignment toolbar for the entire block. This way users can easily align all the content with one click.

**Comment by phpbits** [comment]
@richtabor Added 👍
