### ISSUE TITLE
Hero block content width rangeControl is not functioning properly

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#327]
The ResizableBox works fine, but the RangeControl is not. 

On a side-note, we should set the content width default larger, to `480`

Screenshot:
![screenflow](https://user-images.githubusercontent.com/1813435/53104258-095d7200-34fd-11e9-853a-968c73c0c8cb.gif)

**Comment by phpbits** [comment]
@richtabor Fixed 👍
