### ISSUE TITLE
Inconsistent "reset" button on the Hero block padding DimensionsControl

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#331]
**Describe the bug**
Seems to be some inconsistencies when you hit the reset button on the Hero block's padding DimensionsControl.  The default value associated with the padding size is not always converting to the advanced inputs properly. 

I am able to get it to function properly, but only if I set the value of the paddingSize - and then hit "Advanced" and "Reset". So I suspect it's something to do with the default value. 

**To Reproduce**
1. Add a Hero block
2. Open the sidebar/inspector
3. Click "Advanced"
4. See error (each of the TRBL values should be `60` - the default padding for Huge). 

**Expected behavior**
Each of the padding input values should be set to `60`, which is the default padding for "Huge".

**Screenshots**
![inconsistencies](https://user-images.githubusercontent.com/1813435/53114460-cb1e7d80-3511-11e9-942d-aca5ae3a8283.gif)

**WordPress theme**
TwentyNineteen (though it's irrelevant)

**Additional context**
It's likely not localized to the Hero block, but to the control itself.

**Comment by phpbits** [comment]
@richtabor Fixes included on #332 👍
