### ISSUE TITLE
Set the DimensionsControl "reset" value to the control's default value, not zero

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#332]
**Describe the bug**
The DimensionsControl should reset back to the control's default value, not zero.

**To Reproduce**
1. Add a block that uses our DimensionsControl (Row/Hero)
2. Set the padding to any of the values, other than "None"
3. Click "Advanced"
4. Click "Reset"

**Expected behavior**
When clicking "Reset" the default size for the control should be applied - not "none". 

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/53114685-5f88e000-3512-11e9-99e3-f32a8d312ff4.gif)

**Comment by phpbits** [comment]
@richtabor Fixed 💯

**Comment by richtabor** [comment]
Looks good. 🔥
