### ISSUE TITLE
text alignment is set based on the style selection in the sidebar, but not in the VisualDropdown block toolbar

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#333]
**Describe the bug**
A proper text alignment is set based on the style selection in the block sidebar, but not in the VisualDropdown within the block toolbar. 

**To Reproduce**
1. Add a Hero block
2. Set the style to left, right or centered 
3. See the text alignment for each being properly set
4. Now set the same styles from the VisualDropdown component
5. See the text alignment not being properly set

**Expected behavior**
Both the block sidebar and the block toolbar VisualDropdown should perform the same.

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/53168624-16379f80-35a9-11e9-824c-8350d7f807a2.gif)

**Comment by richtabor** [comment]
@phpbits I'll may take care of this one as I'm not 100% sure if I'm liking how we have the VisualDropdown/Styles implementation just yet. Let me think on it for a bit.

**Comment by richtabor** [comment]
Let's double-back on this one after we get the new CSSGridControl in the toolbar instead of the VisualDropdown component #336

**Comment by phpbits** [comment]
Closing this one since we have #336
