### ISSUE TITLE
Only show the first three style layouts, unless Fullscreen is enabled 

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#334]
Within the VisualDropdown and the Style panel, we have nine layout options (which are made possible via CSS Grid). When the Hero block is not fullscreen, options 1, 2, 3 and 7, 8, 9 are no longer valid— as only the center-left, center-center and center-right are. 

I'd like to find a way to hide the other options unless `fullscreen` is enabled. So by default, only  center-left, center-center and center-right are visible/selectable. But when you toggle fullscreen on, the others are now available.

**Comment by richtabor** [comment]
@phpbits I'll take care of this one as I'm not 100% sure if I'm liking how we have the VisualDropdown/Styles implementation just yet. Let me think on it for a bit.

**Comment by phpbits** [comment]
@richtabor Applied on Inspector control 👍
