### ISSUE TITLE
Make the new CSS Grid control into a CSSGridControl component

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#336]
Let's try to make it one singular component that we can use in either the block toolbar or the sidebar. Perhaps we should have a `toolbar` prop, which lets the component know that we need to render within a DropDown like the VisualDropdown component. That way we can add the same component to both places and it renders properly. 

<img width="296" alt="screen shot 2019-02-21 at 10 34 26 am" src="https://user-images.githubusercontent.com/1813435/53180761-49d3f300-35c4-11e9-8bc4-bf6604d9ff53.png">

**Comment by phpbits** [comment]
@richtabor Added 🥇
