### ISSUE TITLE
Improve Hero block responsiveness in the editor

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#341]
**Describe the bug**
The responsive nature of the Hero block within the editor is not functioning properly. 

**To Reproduce**
1. Add a Hero block
2. Set the content width to 500+
3.Resize the window

**Expected behavior**
The hero area content displays like it does on the front-end, with proper responsiveness.

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/53189993-b22bd000-35d6-11e9-976f-3ee52c9de3fe.gif)

**WordPress theme**
2019

**Comment by phpbits** [comment]
@richtabor Finally figured it out 👍 You can try `hero-block-fixes` branch and let me know how it goes. Thanks!

**Comment by richtabor** [comment]
Looks great!
