### ISSUE TITLE
Hero block FocalPointPicker not properly working

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#342]
**Describe the bug**
The focal point picker of the Hero block is not properly setting the background position selected.

**To Reproduce**
1. Add a Hero block
2. Add a background image
3. Open Background Settings
4. Set the Focal Point picker

**Expected behavior**
The background position of the image changes as you drag around the focal point.

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/53190600-f10e5580-35d7-11e9-8815-afde29d35727.gif)

**WordPress theme**
TwentyNineteen

**Additional context**
It does work on the Row block.

**Comment by phpbits** [comment]
@richtabor Fixed 👍
