### ISSUE TITLE
Buttons block buttons are acting jumping when Stacked on Mobile is turned off

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#344]
**Describe the bug**
Buttons block buttons are acting funny on mobile, when **stacked on mobile** is turned off.

**To Reproduce**
1. Add a Buttons block with content in each
2. Turn off the "Stack on Mobile" setting
3. Publish
4. See error on frontend when the viewport is tiny

**Expected behavior**
They stay side-by-side without any jumping around.

**Screenshots**
Here's a screenshot using the Hero block, but it does the same with just the Buttons block as well.
![screenflow](https://user-images.githubusercontent.com/1813435/53191544-143a0480-35da-11e9-947d-75c1468c81da.gif)

**WordPress theme**
TwentyNineteen

**Comment by phpbits** [comment]
@richtabor I'm not getting the error, are you still experiencing it? Thanks!

![screen capture on 2019-02-22 at 23-37-17](https://user-images.githubusercontent.com/3365507/53252912-f912e600-36fa-11e9-8649-45938b43ec41.gif)

**Comment by richtabor** [comment]
> @richtabor I'm not getting the error, are you still experiencing it? Thanks!
> 
> ![screen capture on 2019-02-22 at 23-37-17](https://user-images.githubusercontent.com/3365507/53252912-f912e600-36fa-11e9-8649-45938b43ec41.gif)

@phpbits, turn off "Stacked on Mobile" for the buttons block - under Advanced. You should see it then.

**Comment by phpbits** [comment]
@richtabor Ah! Buttons has separate stack toggle option, I'll just remove the Advanced option for Hero Block. What do you think?

**Comment by phpbits** [comment]
@richtabor Thanks! I've added the fixes on `buttons-block-fixes` branch. Let me know how it goes.
