### ISSUE TITLE
Remove typography control panel to the Hero block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#345]

**Comment by phpbits** [comment]
@richtabor Added on `hero-block-fixes` branch too 👍

**Comment by richtabor** [comment]
@phpbits Now that I'm playing with it, I think it may be better to not have them on the parent block. What're your thoughts @phpbits ?

**Comment by phpbits** [comment]
@richtabor Me too but I think this would be helpful for font family changes only.

**Comment by richtabor** [comment]
Let's remove it @phpbits . I don't think having all the controls here is working.

**Comment by phpbits** [comment]
@richtabor Done 👍
