### ISSUE TITLE
Hero block padding will not set to "none"

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#347]
**Describe the bug**
Setting the Hero block padding to "none" sets it to "huge" instead.

**To Reproduce**
1. Add a Hero block
2. Set the Padding to None
4. See error (as it does not actually set).

**Expected behavior**
The "none" setting is saved appropriately. 

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/53192436-7431aa80-35dc-11e9-9033-f731c1d2b164.gif)

**Comment by phpbits** [comment]
@richtabor Added fixes on `hero-block-fixes` branch. Thanks!

**Comment by richtabor** [comment]
Looks good!
