### ISSUE TITLE
Click to Tweet block style issue when placed inside of a Row/Column block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#353]
**Describe the bug**
The Click to Tweet block looses it's formatting when placed inside of a Row/Column block. I suspect it's because the block tweaks margin and padding to display the twitter icon to the left of the block.

**To Reproduce**
1. Add a Row block (single col, or variable)
2. Add a Click to Tweet block to a column
3. See error

**Possible solution**
Perhaps we should consider styling the block differently? I'm not entirely sure here.

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/53212401-c7beeb00-3612-11e9-8e86-a36bad878499.gif)

**WordPress theme**
TwentyNineteen (though it's likely independent of the theme).

**Additional context**
There is a support ticket on WordPress.org [here](https://wordpress.org/support/topic/tweet-in-row-loses-format/).

**Comment by phpbits** [comment]
@richtabor Fixed on `click-to-tweet-fixes` based on master branch. Thanks!

**Comment by richtabor** [comment]
@phpbits Perfect. This is ready for a merge.
