### ISSUE TITLE
Should our custom inserter be hidden on layouts that use the Row block?

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#354]
<img width="1250" alt="screen shot 2019-02-22 at 9 16 25 pm" src="https://user-images.githubusercontent.com/1813435/53280366-3d948680-36e7-11e9-9121-a2ef65ccf708.png">

**Comment by phpbits** [comment]
@richtabor I'll create utility class that we can add to parent block for our layouts, then use `!important` to hide the inserter.

**Comment by phpbits** [comment]
@richtabor Added `showInserter` attributes that needs to be defined as false on column to hide inserter. You can try on `disable-inserter-support` branch and insert the Attorney Firm with screenshot. Let me know how it goes. Thanks!

**Comment by richtabor** [comment]
Yea I think this is ok for now at least. 💪

That's just something the developer will have to manually add though to the markup, correct?

**Comment by phpbits** [comment]
@richtabor Yeah, `"showInserter":false` needs to be on the column markup.
