### ISSUE TITLE
Empty button blocks within our Buttons block display fullwidth when stacked

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#360]
**Describe the bug**
Empty button blocks within our Buttons block display fullwidth when the "Stack Buttons"  control is toggled.

**To Reproduce**
1. Add a Buttons block
2. Toggle on Stack Buttons
3. See error

**Expected behavior**
The buttons stack on top of each other, without going fullwidth.

**Screenshots**
![screenflow](https://user-images.githubusercontent.com/1813435/53304282-49945b80-3841-11e9-83a2-871ad11d57b2.gif)

**WordPress theme**
TwentyNineteen

**Comment by phpbits** [comment]
@richtabor Fixed on `empty-button-fixes` branch 👍

**Comment by richtabor** [comment]
Perfect 👏
