### ISSUE TITLE
Remove the "Add New" modal for creating sections

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#361]
It makes sense to have it in place when we have templates and sections, but for now I think it may be more confusing to have it. 
![screenflow](https://user-images.githubusercontent.com/1813435/53304496-025b9a00-3844-11e9-9916-ebf420701d58.gif)

**Comment by phpbits** [comment]
@richtabor Removed on `remove-add-modal` branch. Thanks!

**Comment by richtabor** [comment]
@phpbits Works perfectly - it's ready for merge.
