### ISSUE TITLE
Add button styles to the core Button block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#364]

**Comment by richtabor** [comment]
Here's what I'm thinking for Button styles. 

- [x] Circular
- [x] 3D
- [x] Shadow

![screenflow](https://user-images.githubusercontent.com/1813435/53347610-756a1c80-38e7-11e9-85a9-de10a196e235.gif)

**Comment by phpbits** [comment]
@richtabor Do you think it's good idea to have a fullwidth button style? Thanks!

**Comment by richtabor** [comment]
> @richtabor Do you think it's good idea to have a fullwidth button style? Thanks!

I like that, but the downside is that a fullwidth button would have to be styled as we set it. If it were a button style, we couldn't have a fullwidth outline button (unless we styled it as such). 

But if we could add a Fullwidth ToggleControl to the `core/button` block, which adds an `.is-fullwidth` class to the button - that'd work! You think that's possible?

**Comment by phpbits** [comment]
That could work, I can add that on Advanced Section I think. Or we can just use utility class for our layout purposes. Which do you think is better?

**Comment by richtabor** [comment]
Is there a way to add it to the actual existing inspector controls (instead of "Advanced")?

**Comment by phpbits** [comment]
I think Gutenberg only allows additional options on Advanced but will check it out.

**Comment by phpbits** [comment]
@richtabor Added the advanced option on `button-fullwidth` branch. Let me know your thoughts. Thanks!

**Comment by richtabor** [comment]
Works great @phpbits! Let's use the `.w-100` utility class, instead of `.btn-is-full`.

**Comment by phpbits** [comment]
@richtabor Utility class changed 👍
