### ISSUE TITLE
Row blocks can't have background image if there is only 1 column

### ISSUE THREAD

**Issue by RubiousShaun** [coblocks/coblocks#366]
**Describe the bug**
Row blocks can't have background image if there is only 1 column

**To Reproduce**
1. Create a row block with only one column.
2. Try adding a background image to the row, not the column. You can't. This means it doesn't match other 2-and-3-column blocks

**Comment by richtabor** [comment]
Hey there! We’ve actually already patched this (#301) and will include the fix on the next release coming up shortly. Thanks for checking in and reporting the issue anyhow though! Keep at it!
