### ISSUE TITLE
Add list with no styles

### ISSUE THREAD

**Issue by phpbits** [coblocks/coblocks#368]

**Comment by richtabor** [comment]
Great idea! We could add this easily into 2.0.

**Comment by phpbits** [comment]
@richtabor Added on `no-style-list` branch :) Let me know your thoughts. Thanks!

**Comment by hacknug** [comment]
Just in case you haven't read [this article](https://unfetteredthoughts.net/2017/09/26/voiceover-and-list-style-type-none/), keep in mind, removing list styles with `list-style-type: none;` will affect the element's semantics in some screen readers.

**Comment by phpbits** [comment]
@hacknug Wow! Thanks for the link! I'll see what I can do ;)

**Comment by richtabor** [comment]
Good point @hacknug. @phpbits let's deploy the "zero-width-space" technique and test that. 

Example from that article: 

```
.list li {
  list-style-type: none; /* remove bullets */
}
 
.list li:before {
  content: "\200B"; /* add zero-width space */
}
```

**Comment by phpbits** [comment]
@richtabor @hacknug Fixes added :) First time to know about this bug. Great info! Thanks for letting us know @hacknug
