### ISSUE TITLE
Remove inserter on Row Block for custom layouts

### ISSUE THREAD

**Issue by phpbits** [coblocks/coblocks#372]
Same as what we are doing with out layouts, custom sections created at `CoBlocks > Add New` will not have inserter when inserted via layout block.

Added on `custom-sections-remove-inserter` branch.

![screen capture on 2019-02-28 at 00-14-11](https://user-images.githubusercontent.com/3365507/53504937-e11dd680-3aed-11e9-96e5-b66108d44a0f.gif)

@richtabor What do you think?

**Comment by richtabor** [comment]
Oh nice! So users don't have to do anything more to hide the inserter - it's automatically applied?

**Comment by phpbits** [comment]
@richtabor Yup :) It's only applied on the layout inserted. The inserter will still be visible when they go to CoBlocks layouts and edit them 👍

**Comment by richtabor** [comment]
Looks good!
