### ISSUE TITLE
Masonry Block Column Size Resets

### ISSUE THREAD

**Issue by cchiles** [coblocks/coblocks#376]
**Describe the bug**
When using the Masonry block, removing the width setting setting and changing column size to Extra Large, the width and column size settings are not retained when coming back to the post.

**To Reproduce**
1. Create a post with a Masonry block
2. Add photos to the block
3. In Toolbar, click on _Wide Width_ button to remove the width setting
4. In Block Settings, click on _Column Size: Extra Large_
5. Update post
6. Refresh post

**Expected behavior**
The width and column size settings should be retained.

**WordPress theme**
Tabor

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 72.0.3626.121

**Comment by richtabor** [comment]
Hi @cchiles, I've copied your issue into the Block Gallery repo here: https://github.com/thatplugincompany/block-gallery/issues/23
