### ISSUE TITLE
Background Settings is missing controls when backgroundType is image

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#385]
On the `video-background` branch, the previously deployed background settings are missing. The focal point, fixed background, repeat, display and Remove Image buttons should all be present if the background is set to an image.

**Screenshot (current):** 
<img width="1277" alt="Screenshot 2019-03-15 17 05 46" src="https://user-images.githubusercontent.com/1813435/54461999-9a161f00-4744-11e9-9d81-b9b66219ce1b.png">

**Should be (on master):** 
<img width="1348" alt="Screenshot 2019-03-15 17 06 58" src="https://user-images.githubusercontent.com/1813435/54462039-c2058280-4744-11e9-9a05-c5a7ae0fc505.png">

**Comment by phpbits** [comment]
@richtabor I've hide them since that's from Image Background settings. I'll try if I can integrate the Focal Pointer with video background position though.

**Comment by richtabor** [comment]
> @richtabor I've hide them since that's from Image Background settings. I'll try if I can integrate the Focal Pointer with video background position though.

We don't need FocalPoint with video. What I'm saying is that in the current branch, the background image settings are all missing - even when it's a background image uploaded.
