### ISSUE TITLE
Remove Background button should be more contextual

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#386]
The current "Remove Background" button within the BackgroundImagePanel should be "Remove Image" or "Remove Video" based on the backgroundType attribute. 
<img width="309" alt="Screenshot 2019-03-15 17 12 26" src="https://user-images.githubusercontent.com/1813435/54462268-84edc000-4745-11e9-94a7-a571f568ce54.png">

**Comment by phpbits** [comment]
@richtabor added the fixes on video-background branch.

**Comment by richtabor** [comment]
Perfect 💯
