### ISSUE TITLE
Selecting media with the new DropDown "Edit Background" UI does not work

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#393]
Using the recent `tweak-background-toolbar-menu` branch [(link)](https://github.com/coblocks/coblocks/tree/tweak-background-toolbar-menu), selecting an image from the MediaUpload component is not properly functioning. 

**To replicate:** 
1. Add a background image to a block (I'm using the Hero block). 
2. Select "Edit Background" from the new DropDown within the block toolbar. 
3. Select another image from the Media Gallery. 
4. See error.

**Recording:** 

![ScreenFlow](https://user-images.githubusercontent.com/1813435/54540306-26575a80-496e-11e9-9712-70207cdaf3da.gif)

**Comment by phpbits** [comment]
@richtabor it's the same issue with our experiment for `NavigableMenu` contents. Whenever you clicked outside it's closing.
