### ISSUE TITLE
Add more icons to the Iconblock

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#396]
Add another round of icons for the Icon block, within the `svgs.js` file in the Icon block source. 

Label | Icon | Icon (Outline) | Keywords
------------------- | ------------- | -------------  | -------------
Build | [Download](https://material.io/tools/icons/static/icons/baseline-build-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-build-24px.svg) | blocks block box boxes square build widgets
Credit Card | [Download](https://material.io/tools/icons/static/icons/baseline-credit_card-24px.svg) | — | money cash checkout shop commerce ecommerce
Extension | [Download](https://material.io/tools/icons/static/icons/baseline-extension-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-extension-24px.svg) | puzzle plugin widget team together
Fingerprint | [Download](https://material.io/tools/icons/static/icons/baseline-fingerprint-24px.svg) | — | security bio defense biometric safe secure
Star | [Download](https://material.io/tools/icons/static/icons/baseline-grade-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-grade-24px.svg) | rate vote plus favorite like
Translate | [Download](https://material.io/tools/icons/static/icons/baseline-translate-24px.svg) | — | language global world speech
Update | [Download](https://material.io/tools/icons/static/icons/baseline-update-24px.svg) | — | improve add upload software
Album | [Download](https://material.io/tools/icons/static/icons/baseline-album-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-album-24px.svg) | music microphone song artist creative media audio
New | [Download](https://material.io/tools/icons/static/icons/baseline-new_releases-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-new_releases-24px.svg) | music microphone song artist creative media audio badge
Volume | [Download](https://material.io/tools/icons/static/icons/baseline-volume_up-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-volume_up-24px.svg) | music microphone song artist creative media audio
Email | [Download](https://material.io/tools/icons/static/icons/baseline-alternate_email-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-alternate_email-24px.svg) | email mail os read letter
Devices | [Download](https://material.io/tools/icons/static/icons/baseline-devices-24px.svg) | — | computer ipad surface apple device pc desk office
Keyboard | [Download](https://material.io/tools/icons/static/icons/baseline-keyboard-24px.svg) | — | computer ipad surface apple device pc desk office
Headset | [Download](https://material.io/tools/icons/static/icons/baseline-headset-24px.svg) | — | microphone audio beats bose headphones
Paint | [Download](https://material.io/tools/icons/static/icons/baseline-format_paint-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-format_paint-24px.svg) | palette design colors artist creative media
Brush | [Download](https://material.io/tools/icons/static/icons/baseline-brush-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-brush-24px.svg) | palette design colors artist creative media paint paintbrush
Vintage Filter | [Download](https://material.io/tools/icons/static/icons/baseline-filter_vintage-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-filter_vintage-24px.svg) | flower camera photography artist creative
Flare | [Download](https://material.io/tools/icons/static/icons/baseline-flare-24px.svg) | — | flower camera photography artist creative
Layers | [Download](https://material.io/tools/icons/static/icons/baseline-layers-24px.svg) | — | design creative build develop engineer
Shipping | [Download](https://material.io/tools/icons/static/icons/baseline-local_shipping-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-local_shipping-24px.svg) | shop commence ecommence woo cart ship
Inclusive | [Download](https://material.io/tools/icons/static/icons/baseline-inclusive-24px.svg) | — | diversity respect equality world peace infinite infinity
Snowflake | [Download](https://material.io/tools/icons/static/icons/baseline-ac_unit-24px.svg) | — | cold ice frozen chill winter season global
School | [Download](https://material.io/tools/icons/static/icons/baseline-school-24px.svg) | — | education graduate graduation degree diploma college
Fire | [Download](https://material.io/tools/icons/static/icons/baseline-whatshot-24px.svg) | — | hot trending trendy design
Poll | [Download](https://material.io/tools/icons/static/icons/baseline-poll-24px.svg) | [Download](https://material.io/tools/icons/static/icons/outline-poll-24px.svg) | chart graph stats data graph

**Comment by phpbits** [comment]
@richtabor adding them, got issue with `update` svg though. It's returning error when added. I'll let you know when it's all added. Thanks!

**Comment by richtabor** [comment]
> @richtabor adding them, got issue with `update` svg though. It's returning error when added. I'll let you know when it's all added. Thanks!

May be an issue with the mask it uses.  Let's skip that one.

**Comment by phpbits** [comment]
@richtabor Added all icons except `update` and `inclusive` on branch `more-icons`.

**Comment by richtabor** [comment]
Looks good!
