### ISSUE TITLE
Background image pre-loading is not working

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#421]
We have an existing pre-loading effect (similar to core, using isBlobURL) in our Features, Media Card, Row and Column blocks - but it does not seem to be functioning properly. 

`{ isBlobURL( backgroundImg ) && <Spinner /> }` is not working anymore.

- [x] Features
- [x] Feature
- [x] Media Card
- [x] Row
- [x] Column
- [x] Hero

**Comment by phpbits** [comment]
@richtabor Added and tested on `fix-preloader` branch 👍
