### ISSUE TITLE
Existing blocks using the BackgroundPanel need to be updated to receive video

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#422]
Currently only the Hero block receives video properly. We need to update the following blocks to receive the same functionality (and ensure backwards compatibility with CoBlocks 1.9.3 - ). 

- [x] Row
- [x] Column
- [x] Media Card
- [x] Features
- [x] Hero

Current (Row block):
<img width="942" alt="Screenshot 2019-03-23 14 07 47" src="https://user-images.githubusercontent.com/1813435/54869885-1926db00-4d75-11e9-8fc0-408d0c95a278.png">

@phpbits Is this something we should build a reusable component within BackgroundImagePanel, instead of having the same exact markup/options used in each block?

**Comment by phpbits** [comment]
@richtabor Done on `apply-video-blocks` branch 👍
