### ISSUE TITLE
Display issues with a single column Row block with a video background 

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#441]
I'm using the `apply-video-backgrounds` branch to replicate the issue. This is the last issue for that branch. 

![ScreenFlow](https://user-images.githubusercontent.com/1813435/55019650-b1b69880-4fcb-11e9-960c-c295e2b148e5.gif)

**Comment by phpbits** [comment]
@richtabor Fixed the issue by adding back left and top zero px positioning. Thanks!
