### ISSUE TITLE
Unexpected error occurs when deactivating Gutenberg 5.3 

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#445]
Deactivating the Gutenberg 5.3 plugin (and using WordPress 5.1) causes the following issue: 
`TypeError: undefined is not an object (evaluating 'e.preferences.insertUsage[t]')`. Reactivating the plugin removes the error. 

<img width="1563" alt="Screenshot 2019-03-27 15 43 11" src="https://user-images.githubusercontent.com/1813435/55107185-0a0e9880-50a7-11e9-97db-d16665d0bdbb.png">

**Comment by phpbits** [comment]
@richtabor I'm not getting this issue on WordPress 5.0 and 5.1.1, do you have any other plugins activated? Thanks!
