### ISSUE TITLE
Improve logic for left/right/center contentAlign in the Banner block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#451]
The block should auto-assign the `contentAlign` variable based on the currently selected layout , similar to how we've done it in our Hero block. 

The following logic should be in place: 

1. Set the layout to `center` /  the contentAlign variable is also set to `center`
2. Set the layout to `left` /  the contentAlign variable is also set to `left`
3. Set the layout to `right` /  the contentAlign variable is also set to `left` (_we don't want right-aligned text here_). 

It's important to note that for left/right `contentAlign` settings, the Buttons block included in InnerBlocks TEMPLATE should always be set to the far left, or far right. The `contentAlign` attribute should not affect the way the Buttons/Button blocks display.

**Comment by phpbits** [comment]
@richtabor Pushed this changes on `add/banner-block` branch. Thanks!
