### ISSUE TITLE
Add ResizableBox height to Hero Block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#454]
Let's try and add the same ResizableBox height functionality that we've baked into the Banner block to the Hero block. Do you think that's possible @phpbits, considering we already have a horizontal resize inside of it? It'd be a great addition if so.

One consideration we'll need to make is that if the Hero block has `fullScreen` enabled, we'll need to disable the ResizableBox functionality. 🤔

**Comment by phpbits** [comment]
@richtabor Added on `update/hero-block-height` branch 👍
