### ISSUE TITLE
Banner block > Buttons block is acting up

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#456]
I'm experiencing odd behavior with the Buttons block (see screencast below). Essentially the text is not staying on one line in the button.

![ScreenFlow](https://user-images.githubusercontent.com/1813435/55406481-32284c80-552a-11e9-82e6-ca3b93dd84bf.gif)

**Comment by phpbits** [comment]
Are you using 2019 theme also? I'm getting the correct one :

<img width="1005" alt="Screen Shot 2019-04-04 at 8 30 22 PM" src="https://user-images.githubusercontent.com/3365507/55555745-8bee6980-5718-11e9-9aab-fc8da14260d6.png">

**Comment by richtabor** [comment]
Odd, it's working now!
