### ISSUE TITLE
Additional class not being assigned to the Row block within the editor

### ISSUE THREAD

**Issue by benjaminluoma** [coblocks/coblocks#459]
Hi! Great plugin. Love it.

It would be nice if I could make use of the "Additional CSS Class" field with coblocks rows like I can with the default blocks. Of course the classes work fine on the frontend but I'd like to see the styles related to those classes in the editor when I put my pages together. Make sense?

Thanks!

**Comment by richtabor** [comment]
Hey Ben! Glad you like CoBlocks. :) 

Is that class just not showing up within the editor's instance? Or are you looking for help on how to add custom styles to the editor? If it's the latter, [I've written a guide](https://richtabor.com/add-wordpress-theme-styles-to-gutenberg/) to help folks add styles to the editor. You need to load those styles in separately.

**Comment by benjaminluoma** [comment]
Thanks for the quick response Rich. So... it's the former. I'm adding a class to my row block and in the editor I'd like to see the styles reflected but it doesn't seem to work out. 

For example I've added .test-class to a default cover image block:

![image](https://user-images.githubusercontent.com/2529580/55447083-eb693f80-5587-11e9-8cb7-adca21e2a830.png)

My classes aren't being added to my row blocks in the editor. They work out fine on the frontend.

**Comment by richtabor** [comment]
Thanks for that insight @benjaminluoma, I've figured out what's happening and I'll include the fix in the next update scheduled for tomorrow morning.
