### ISSUE TITLE
Row block resizable handle is misaligned in Gutenberg 5.4

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#460]
<img width="779" alt="Screenshot 2019-04-03 09 33 10" src="https://user-images.githubusercontent.com/1813435/55482949-94994f80-55f3-11e9-8b03-2367d3d558b6.png">

**Comment by phpbits** [comment]
@richtabor Added fixes on `fixes/5.4-compatibility` branch 👍

**Comment by richtabor** [comment]
Looks good!
