### ISSUE TITLE
Gutter should not be applied to the last button in the Buttons block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#461]
![ScreenFlow](https://user-images.githubusercontent.com/1813435/55483399-7bdd6980-55f4-11e9-9820-45797d096174.gif)

**Comment by phpbits** [comment]
@richtabor Seems to be working fine on my end. I'm not getting the issue using 2019 and CoBlocks theme.

**Comment by phpbits** [comment]
@richtabor Added fixes on fixes/5.4-compatibility branch too 👍
