### ISSUE TITLE
Advanced size in Icon Block causes the UI to jump

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#462]
The UI should not jump when Advanced sizing is enabled. See screencast: 
![ScreenFlow](https://user-images.githubusercontent.com/1813435/55483719-34a3a880-55f5-11e9-91d4-35d5584cbb5d.gif)

**Comment by phpbits** [comment]
@richtabor Added fixes on fixes/5.4-compatibility branch 👍
