### ISSUE TITLE
Pressing "enter" while searching for a gif in the Gif Block causes a page refresh

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#463]
Pressing "enter" should not cause the page to reload.

![ScreenFlow](https://user-images.githubusercontent.com/1813435/55484275-36ba3700-55f6-11e9-89cb-979bbe5d7901.gif)

**Comment by phpbits** [comment]
@richtabor Added fixes on `fixes/5.4-compatibility` branch 👍
