### ISSUE TITLE
Center align labels on the Map block Styles panel

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#464]
The Styles panel within the Map block Inspector sidebar should have centered labels and look just like the Styles dropdown in the block toolbar. There needs to be a bit more margin-top applied to the labels as well (so they match the labels in the block toolbar). 

<img width="1277" alt="Screenshot 2019-04-03 09 58 45" src="https://user-images.githubusercontent.com/1813435/55484757-13dc5280-55f7-11e9-86c8-f51bde04093e.png">

**Comment by phpbits** [comment]
@richtabor Added fixes on fixes/5.4-compatibility branch 👍
