### ISSUE TITLE
Gutenberg 5.4 Compatibility

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#465]
Reviewing the blocks and each component within with Gutenberg 5.4. 

Blocks: 
- [x] Row (#460)
- [x] Column
- [x] Accordion
- [x] Accordion Item
- [x] Buttons
- [x ] Hero
- [x] Click to Tweet
- [x] Features
- [x] Dynamic HR
- [x] Gif (#463)
- [x] Gist
- [x] Highlight
- [x] Icon (#462)
- [ ] Map (#464)
- [x] Media Card
- [x] Pricing Table
- [x] Shape Divider
- [x] Social

**Comment by phpbits** [comment]
@richtabor Fixed the issues aside from Buttons block. Seems to be working fine on my end. Thanks!
