### ISSUE TITLE
Tweak Gif block and Media Card Alt Text help text to match the core Image block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#467]
Current:
<img width="324" alt="Screenshot 2019-04-03 10 24 16" src="https://user-images.githubusercontent.com/1813435/55486634-a4686200-55fa-11e9-8d53-d82f3b8e9169.png">

From core: 
<img width="299" alt="Screenshot 2019-04-03 10 23 35" src="https://user-images.githubusercontent.com/1813435/55486618-9e728100-55fa-11e9-9f8f-818ad43b8ba5.png">

**Comment by phpbits** [comment]
@richtabor Added fixes on fixes/5.4-compatibility branch 👍
