### ISSUE TITLE
Use minHeight instead of Height for the Hero block

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#469]
This way responsiveness is much better, instead of forcing a height, for when the content is greater than the height selected.

**Comment by richtabor** [comment]
@phpbits I've done the editor/save function, but we'll need to tweak the `class-coblocks-generated-styles.php` file for this.

**Comment by phpbits** [comment]
@richtabor Changing the generated style will affect all blocks. I think we've discussed this before, using `height` is better than `min-height` to override block height. If in any case a block have height attributes min-height won't work. Let me know your thoughts. Thanks!
