### ISSUE TITLE
Banner block should use the BackgroundVideo() function

### ISSUE THREAD

**Issue by richtabor** [coblocks/coblocks#474]
The block is currently manually generating the markup for the background video (for both the edit and save functions).

It should be using the `{ BackgroundVideo( attributes ) }` function that we've added to the other blocks which use the `BackgroundPanel`.

**Comment by phpbits** [comment]
Fixed on `fixes/banner-block` branch. Thanks!

**Comment by richtabor** [comment]
Lookin' good! Thanks!
